@startuml
skinparam classAttributeIconSize 0

class Main {
    +int terminar;
    +float can;
    + ConversorMoneda(can)
        + DolaraPesoMexicano(can)
        + DolaraQuetzal(can)
        + DolaraLibra(can)
        + DolaraFranco(can)
}

class ConversorMoneda {
    + String moneda1=Dolar;
    + String moneda2=PesoMX;
    + String moneda3=Quetzal;
    + String moneda4=Libra Egipcia;
    + String moneda5=Franco Suizo;
    + String moneda6=Peso Cubano;
    + double conversion;
    + ConversorMoneda(float cantidad)
    + DolaraPesoMexicano(float cantidad)
    + DolaraQuetzal(float cantidad)
    + DolaraLibra(float cantidad)
    + DolaraFranco(float cantidad)


}

Main <|--- ConversorMoneda
@enduml